name: my_crypto
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


    #DI
  get_it: ^7.2.0
  injectable: ^1.5.3
  provider: ^6.0.2
  equatable: ^2.0.3


  #DB
  hive: ^2.1.0
  flutter_secure_storage: ^5.0.2


  #SM
  rxdart: ^0.27.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  auto_route: ^3.2.4
  dartz: ^0.10.1
  either_dart: ^0.1.4

  #REST
  dio: ^4.0.4
  retrofit: ^3.0.1+1

  #socket_io_client: ^2.0.0-beta.4-nullsafety.0
  #web_socket_channel: ^2.1.0

  #UTILITY
  intl: ^0.17.0
  easy_localization: ^3.0.0
  local_auth: ^1.1.11
  flutter_svg: ^1.0.3
  internet_connection_checker: ^0.0.1+2
  connectivity_plus: ^2.2.0
  firebase_core: ^1.11.0
  json_annotation: ^4.4.0


  #DESIGN
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.3.1
  charts_flutter: ^0.12.0
  fl_chart: 0.40.2



  #OTHER
  logger: ^1.1.0
  firebase_analytics: ^9.1.3
  firebase_app_check: ^0.0.6+8
  firebase_auth: ^3.3.12
  firebase_crashlytics: ^2.6.1
  cloud_firestore: ^3.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.2+1
  build_runner: ^2.1.7
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4
  retrofit_generator: ^4.0.1
  auto_route_generator: ^3.2.3

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true


flutter:
  assets:
    - assets/
    - assets/langList/
    - assets/svgIcons/
    - assets/pngIcons/


  uses-material-design: true


